# Generated by Django 5.1.5 on 2025-01-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_personmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmodel',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
