# Generated by Django 5.1.5 on 2025-01-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_personmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='date',
            new_name='birthday',
        ),
    ]
